
-- schema DDL for mapping dependencies
CREATE SCHEMA UTILITYCO_C2M#ASSET;

-- All object DDL for mapping dependencies

  CREATE TABLE "UTILITYCO_C2M#ASSET"."CI_SP" 
   (	"DISCON_LOC_CD" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"SP_ID" CHAR(10 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SP_TYPE_CD" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"PREM_ID" CHAR(10 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"SP_STATUS_FLG" CHAR(2 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"INSTALL_DT" DATE NOT NULL ENABLE, 
	"SP_SRC_STATUS_FLG" CHAR(2 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"MR_CYC_CD" CHAR(16 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"MR_RTE_CD" CHAR(16 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"MTR_LOC_CD" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"MR_CYC_RTE_SEQ" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"FAC_LVL_1_CD" CHAR(8 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"MTR_LOC_DETAILS" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"FAC_LVL_2_CD" CHAR(8 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"FAC_LVL_3_CD" CHAR(8 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL ENABLE, 
	"DESCRLONG" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"ABOLISH_DT" DATE, 
	"OVRD_PREM_FLD_INFO_FLG" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" DEFAULT 'N' NOT NULL ENABLE, 
	"MR_INSTR_CD" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"MR_WARN_CD" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"KEY_SW" CHAR(1 CHAR) COLLATE "USING_NLS_COMP" DEFAULT 'N' NOT NULL ENABLE, 
	"KEY_ID" CHAR(10 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"OK_TO_ENTER_SW" CHAR(1 CHAR) COLLATE "USING_NLS_COMP" DEFAULT 'N' NOT NULL ENABLE, 
	"MR_INSTR_DETAILS" VARCHAR2(250 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"SP_DATA_AREA" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("SP_DATA_AREA") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  CACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  CREATE UNIQUE INDEX "UTILITYCO_C2M#ASSET"."XM226P0" ON "UTILITYCO_C2M#ASSET"."CI_SP" ("SP_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "UTILITYCO_C2M#ASSET"."CI_SP" ADD PRIMARY KEY ("SP_ID")
  USING INDEX "UTILITYCO_C2M#ASSET"."XM226P0"  ENABLE;


  CREATE TABLE "UTILITYCO_C2M#ASSET"."CI_SP_TYPE" 
   (	"SP_TYPE_CD" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SVC_TYPE_CD" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"TREND_CL_CD" CHAR(8 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"SP_SUBTYPE_FLG" CHAR(2 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"FA_TYPE_PROF_CD" CHAR(8 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL ENABLE, 
	"ALLOW_MR_ROUTE_SW" CHAR(1 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"START_STOP_GEO_TYP" CHAR(8 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"MULT_RTE_USAGE_FLG" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"EXT_SERV_REQ_FLG" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' '
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "UTILITYCO_C2M#ASSET"."XC235P0" ON "UTILITYCO_C2M#ASSET"."CI_SP_TYPE" ("SP_TYPE_CD") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "UTILITYCO_C2M#ASSET"."CI_SP_TYPE" ADD PRIMARY KEY ("SP_TYPE_CD")
  USING INDEX "UTILITYCO_C2M#ASSET"."XC235P0"  ENABLE;


  CREATE TABLE "UTILITYCO_C2M#ASSET"."C1_COMM_RTE_TYPE" 
   (	"COMM_RTE_TYPE_CD" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"BUS_OBJ_CD" CHAR(30 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"COMM_RTE_METH_FLG" VARCHAR2(254 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"FMT_ALG_CD" CHAR(12 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"ALW_DND_FLG" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CND_VERIF_STATUS_FLG" CHAR(4 CHAR) COLLATE "USING_NLS_COMP", 
	"BO_DATA_AREA" CLOB COLLATE "USING_NLS_COMP", 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL ENABLE, 
	"ALW_PCT_STATUS_FLG" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("BO_DATA_AREA") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  CACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  CREATE UNIQUE INDEX "UTILITYCO_C2M#ASSET"."C1C077P0" ON "UTILITYCO_C2M#ASSET"."C1_COMM_RTE_TYPE" ("COMM_RTE_TYPE_CD") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "UTILITYCO_C2M#ASSET"."C1_COMM_RTE_TYPE" ADD PRIMARY KEY ("COMM_RTE_TYPE_CD")
  USING INDEX "UTILITYCO_C2M#ASSET"."C1C077P0"  ENABLE;


  CREATE TABLE "UTILITYCO_C2M#ASSET"."C1_PER_CONTDET" 
   (	"C1_CONTACT_ID" CHAR(10 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PER_ID" CHAR(10 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"COMM_RTE_TYPE_CD" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"CONTACT_VALUE" VARCHAR2(254 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"CND_PRIMARY_FLG" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"CONTACT_VALUE_EXT" CHAR(6 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"DND_START_TM" DATE, 
	"DND_END_TM" DATE, 
	"CND_VERIF_STATUS_FLG" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"CND_ACTINACT_FLG" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL ENABLE, 
	"CONTACT_NAME" CHAR(100 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"CONTACT_EXT_ID" VARCHAR2(254 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "UTILITYCO_C2M#ASSET"."C1T009P0" ON "UTILITYCO_C2M#ASSET"."C1_PER_CONTDET" ("C1_CONTACT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "UTILITYCO_C2M#ASSET"."C1_PER_CONTDET" ADD PRIMARY KEY ("C1_CONTACT_ID")
  USING INDEX "UTILITYCO_C2M#ASSET"."C1T009P0"  ENABLE;


  CREATE TABLE "UTILITYCO_C2M#ASSET"."CI_PER" 
   (	"PER_ID" CHAR(10 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"LANGUAGE_CD" CHAR(3 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"PER_OR_BUS_FLG" CHAR(2 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"LS_SL_FLG" CHAR(2 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"LS_SL_DESCR" VARCHAR2(1000 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"EMAILID" VARCHAR2(254 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"OVRD_MAIL_NAME1" VARCHAR2(254 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"OVRD_MAIL_NAME2" VARCHAR2(254 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"OVRD_MAIL_NAME3" VARCHAR2(254 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"ADDRESS1" VARCHAR2(254 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"ADDRESS2" VARCHAR2(254 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"ADDRESS3" VARCHAR2(254 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"ADDRESS4" VARCHAR2(254 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"CITY" VARCHAR2(90 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"NUM1" CHAR(6 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"NUM2" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"COUNTY" VARCHAR2(90 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"POSTAL" CHAR(12 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"HOUSE_TYPE" CHAR(2 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"GEO_CODE" CHAR(11 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"IN_CITY_LIMIT" CHAR(1 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"STATE" CHAR(6 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"COUNTRY" CHAR(3 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL ENABLE, 
	"RECV_MKTG_INFO_FLG" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" DEFAULT 'NRCV' NOT NULL ENABLE, 
	"WEB_PASSWD" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"WEB_PWD_HINT_FLG" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"WEB_PASSWD_ANS" VARCHAR2(60 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"PER_DATA_AREA" CLOB COLLATE "USING_NLS_COMP", 
	"TIME_ZONE_CD" CHAR(10 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("PER_DATA_AREA") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  CACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  CREATE UNIQUE INDEX "UTILITYCO_C2M#ASSET"."XM169P0" ON "UTILITYCO_C2M#ASSET"."CI_PER" ("PER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "UTILITYCO_C2M#ASSET"."CI_PER" ADD PRIMARY KEY ("PER_ID")
  USING INDEX "UTILITYCO_C2M#ASSET"."XM169P0"  ENABLE;


  CREATE TABLE "UTILITYCO_C2M#ASSET"."CI_PER_ID" 
   (	"PER_ID" CHAR(10 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"ID_TYPE_CD" CHAR(8 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PER_ID_NBR" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"PRIM_SW" CHAR(1 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL ENABLE, 
	"ENCR_PER_ID_NBR" VARCHAR2(172 CHAR) COLLATE "USING_NLS_COMP", 
	"HASH_PER_ID_NBR" VARCHAR2(88 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "UTILITYCO_C2M#ASSET"."XM170P0" ON "UTILITYCO_C2M#ASSET"."CI_PER_ID" ("PER_ID", "ID_TYPE_CD") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "UTILITYCO_C2M#ASSET"."CI_PER_ID" ADD PRIMARY KEY ("PER_ID", "ID_TYPE_CD")
  USING INDEX "UTILITYCO_C2M#ASSET"."XM170P0"  ENABLE;


  CREATE TABLE "UTILITYCO_C2M#ASSET"."CI_PER_NAME" 
   (	"PER_ID" CHAR(10 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SEQ_NUM" NUMBER(3,0) NOT NULL ENABLE, 
	"ENTITY_NAME" VARCHAR2(254 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"NAME_TYPE_FLG" CHAR(4 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL ENABLE, 
	"PRIM_NAME_SW" CHAR(1 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE, 
	"ENTITY_NAME_UPR" VARCHAR2(254 CHAR) COLLATE "USING_NLS_COMP" DEFAULT ' ' NOT NULL ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "UTILITYCO_C2M#ASSET"."XM171P0" ON "UTILITYCO_C2M#ASSET"."CI_PER_NAME" ("PER_ID", "SEQ_NUM") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "UTILITYCO_C2M#ASSET"."CI_PER_NAME" ADD PRIMARY KEY ("PER_ID", "SEQ_NUM")
  USING INDEX "UTILITYCO_C2M#ASSET"."XM171P0"  ENABLE;


